### ISSUE TITLE
Use a new Twig parser

### ISSUE THREAD

**Issue by Kocal** [Kocal/prettier-plugin-twig#15]
[Twing](https://github.com/ericmorand/twing) is really nice and works well, but there is too much issues: 
  - whitespace control modifier are not preserved: #4, https://github.com/ericmorand/twing/issues/321, https://github.com/ericmorand/twing/pull/326
  - unknown filters thrown an error (`{{ foo | bar }}`):
![Sélection_508](https://user-images.githubusercontent.com/2103975/55633346-72066280-57bc-11e9-8524-9457a5ff2779.png)
  - macros/blocks/traits (#14) are handled differenlty (with references) 

IMO, I think the best solution is to use a new parser that will be especially written for this plugin, a parser which takes code, lex it, parse it, and returns AST.

**Comment by panoply** [comment]
@Kocal Have you looked at [PrettyDiff](http://prettydiff.com)? I recently explored beautification of the Liquid language (which is similar to Twig) on a small VSCode [plugin](https://github.com/panoply/vscode-shopify-liquid) I maintain.

**Comment by Kocal** [comment]
Hi, I've tried the `Parse Table` functionality on https://prettydiff.com/ and https://prettydiff.com/2 but this gives really weird output.

Example, for the input code `{% set foo = [1, 2, 3] %}`, prettydiff parser output:
```json
{
  // ...
  "token": [
    "{% set foo = [1, 2, 3] %}"
  ],
  // ...
}
```

And that's unusable in my case, I need the lexer to output an array of tokens like that:
- block start
- name `set`
- name `foo`
- operator `=`
- punctuation `[`
- number type `1`
- punctuation `,`
- number type `2`
- punctuation `,`
- number type `3`
- punctuation `]`
- block close
- eof

And since prettydiff is language-aware, I don't think this will even happens :confused: 

But thanks for the proposal :)

**Comment by Kocal** [comment]
Hum, in fact I think I will still use Twing but only as a lexer (which is pretty nice!).

Twing gives us the possibility to use our own parser, so let's abuse it.
